dist: jammy
language: node_js
node_js: 20
anchor: &npm npm # This is here to show comment and preserved
cache: *npm
install: npm ci
stages:
  - lint
  - test
  - name: auto-bump
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint

    - &test
      stage: test
      name: test-update-node16
      node_js: '16'
      script: npm run test:all
      after_success: npm run publish-coverage
    - <<: *test
      name: test-update-node18
      node_js: '18'

    - <<: *test
      name: test-update-node20
      node_js: '20'

    - stage: auto-bump
      name: auto-bump
      script: ./scripts/self-update.sh
