dist: jammy
language: node_js
node_js: 20
anchor: &npm npm # This is here to show comment and preserved
cache: *npm
install: npm ci
stages:
  - lint
  - test
  - name: auto-bump
    if: branch = master AND type = push

jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint

    - &test
      stage: test
      name: test-update-node18
      node_js: '18'
      script: npm run test:all

    - <<: *test
      name: test-update-node20
      node_js: '20'

    - <<: *test
      name: test-update-node22
      node_js: '22'

    - stage: auto-bump
      name: auto-bump
      before_script:
        - git config --global user.email "tech@coorpacademy.com"
        - git config --global user.name "Coorpacademy Bot"
      script: ./scripts/self-update.sh
