language: node_js
node_js:
  - 8.16.2
# This is here to show comment is preserved
cache: &yarn yarn
install: *yarn
script: yarn test
deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/self-update.sh
    'on':
      branch: master
