language: node_js
node_js:
  - 8.16.2
# This is here to show comment is preserved
anchor: &npm npm
cache: *npm
install: npm ci
script:
  - npm test
  - ./scripts/integration-test.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/self-update.sh
    'on':
      branch: master
