language: node_js
node_js: 12
anchor: &npm npm # This is here to show comment and preserved
cache: *npm
install: npm ci
stages:
  - lint
  - test
  - name: auto-bump
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint

    - &test
      stage: test
      name: test-update-node12
      node_js: '12'
      script: npm run test:all
      after_success: npm run publish-coverage
    - <<: *test
      name: test-update-node14
      node_js: '14'

    - stage: auto-bump
      name: auto-bump
      script: ./scripts/self-update.sh
