language: node_js
node_js:
  - 8.15.1
cache: yarn

install: yarn

script: yarn test

deploy:
  - provider: script
    skip_cleanup: true
    script: git checkout master && node ./src/index.js --token $GH_TOKEN --auto
    'on':
      branch: master
