language: node_js
node_js:
  - 10
  - 12
  - 14
# This is here to show comment is preserved
anchor: &npm npm
cache: *npm
install: npm ci
script: npm test
after_success: npm run publish-coverage
deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/self-update.sh
    'on':
      branch: master
