
name: Update node CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config --global user.email "update-node@coorpacademy.com" && git config --global user.name "Update Node"
      - run: npm ci
      - run: npm test
      - name: Upload coverage
        uses: codecov/codecov-action@v5
